
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightEQUALSCOMMA DIVIDE ELSE EQUALS ID IF INT LBRACE LPAREN MINUS NUMBER PLUS PRINT RBRACE RETURN RPAREN SEMICOLON TIMES WHILEprogram : declaration_listdeclaration_list : declaration_list declaration\n                        | declarationdeclaration : function_declaration\n                   | statementfunction_declaration : INT ID LPAREN parameter_list RPAREN LBRACE statement_list RBRACE\n                            | INT ID LPAREN RPAREN LBRACE statement_list RBRACEparameter_list : parameter_list COMMA parameter\n                      | parameterparameter : INT IDstatement_list : statement_list statement\n                      | statementstatement : INT ID SEMICOLON\n                 | INT ID EQUALS expression SEMICOLONstatement : ID EQUALS expression SEMICOLONstatement : RETURN expression SEMICOLON\n                 | RETURN SEMICOLONstatement : PRINT LPAREN expression RPAREN SEMICOLONexpression : termterm : term TIMES factor\n            | term DIVIDE factorterm : factorfactor : NUMBERfactor : IDfactor : ID LPAREN argument_list RPAREN\n              | ID LPAREN RPARENargument_list : argument_list COMMA expression\n                     | expressionfactor : LPAREN expression RPARENexpression : expression PLUS term\n                  | expression MINUS term'
    
_lr_action_items = {'INT':([0,2,3,4,5,10,14,21,22,25,38,50,51,52,55,56,59,60,62,64,65,66,],[6,6,-3,-4,-5,-2,-17,33,-13,-16,-15,33,58,-14,-18,58,58,-12,58,-7,-11,-6,]),'ID':([0,2,3,4,5,6,8,10,12,14,19,20,22,23,25,26,27,28,29,30,33,38,51,52,54,55,56,58,59,60,62,64,65,66,],[7,7,-3,-4,-5,11,18,-2,18,-17,18,18,-13,18,-16,18,18,18,18,18,48,-15,7,-14,18,-18,7,63,7,-12,7,-7,-11,-6,]),'RETURN':([0,2,3,4,5,10,14,22,25,38,51,52,55,56,59,60,62,64,65,66,],[8,8,-3,-4,-5,-2,-17,-13,-16,-15,8,-14,-18,8,8,-12,8,-7,-11,-6,]),'PRINT':([0,2,3,4,5,10,14,22,25,38,51,52,55,56,59,60,62,64,65,66,],[9,9,-3,-4,-5,-2,-17,-13,-16,-15,9,-14,-18,9,9,-12,9,-7,-11,-6,]),'$end':([1,2,3,4,5,10,14,22,25,38,52,55,64,66,],[0,-1,-3,-4,-5,-2,-17,-13,-16,-15,-14,-18,-7,-6,]),'EQUALS':([7,11,63,],[12,23,23,]),'SEMICOLON':([8,11,13,15,16,17,18,24,37,39,40,41,42,44,46,47,53,63,],[14,22,25,-19,-22,-23,-24,38,52,-30,-31,-20,-21,-26,-29,55,-25,22,]),'NUMBER':([8,12,19,20,23,26,27,28,29,30,54,],[17,17,17,17,17,17,17,17,17,17,17,]),'LPAREN':([8,9,11,12,18,19,20,23,26,27,28,29,30,54,],[19,20,21,19,30,19,19,19,19,19,19,19,19,19,]),'PLUS':([13,15,16,17,18,24,31,32,37,39,40,41,42,44,45,46,53,61,],[26,-19,-22,-23,-24,26,26,26,26,-30,-31,-20,-21,-26,26,-29,-25,26,]),'MINUS':([13,15,16,17,18,24,31,32,37,39,40,41,42,44,45,46,53,61,],[27,-19,-22,-23,-24,27,27,27,27,-30,-31,-20,-21,-26,27,-29,-25,27,]),'RBRACE':([14,22,25,38,52,55,59,60,62,65,],[-17,-13,-16,-15,-14,-18,64,-12,66,-11,]),'RPAREN':([15,16,17,18,21,30,31,32,34,36,39,40,41,42,43,44,45,46,48,53,57,61,],[-19,-22,-23,-24,35,44,46,47,49,-9,-30,-31,-20,-21,53,-26,-28,-29,-10,-25,-8,-27,]),'COMMA':([15,16,17,18,34,36,39,40,41,42,43,44,45,46,48,53,57,61,],[-19,-22,-23,-24,50,-9,-30,-31,-20,-21,54,-26,-28,-29,-10,-25,-8,-27,]),'TIMES':([15,16,17,18,39,40,41,42,44,46,53,],[28,-22,-23,-24,28,28,-20,-21,-26,-29,-25,]),'DIVIDE':([15,16,17,18,39,40,41,42,44,46,53,],[29,-22,-23,-24,29,29,-20,-21,-26,-29,-25,]),'LBRACE':([35,49,],[51,56,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declaration_list':([0,],[2,]),'declaration':([0,2,],[3,10,]),'function_declaration':([0,2,],[4,4,]),'statement':([0,2,51,56,59,62,],[5,5,60,60,65,65,]),'expression':([8,12,19,20,23,30,54,],[13,24,31,32,37,45,61,]),'term':([8,12,19,20,23,26,27,30,54,],[15,15,15,15,15,39,40,15,15,]),'factor':([8,12,19,20,23,26,27,28,29,30,54,],[16,16,16,16,16,16,16,41,42,16,16,]),'parameter_list':([21,],[34,]),'parameter':([21,50,],[36,57,]),'argument_list':([30,],[43,]),'statement_list':([51,56,],[59,62,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> declaration_list','program',1,'p_program','parser.py',20),
  ('declaration_list -> declaration_list declaration','declaration_list',2,'p_declaration_list','parser.py',25),
  ('declaration_list -> declaration','declaration_list',1,'p_declaration_list','parser.py',26),
  ('declaration -> function_declaration','declaration',1,'p_declaration','parser.py',34),
  ('declaration -> statement','declaration',1,'p_declaration','parser.py',35),
  ('function_declaration -> INT ID LPAREN parameter_list RPAREN LBRACE statement_list RBRACE','function_declaration',8,'p_function_declaration','parser.py',40),
  ('function_declaration -> INT ID LPAREN RPAREN LBRACE statement_list RBRACE','function_declaration',7,'p_function_declaration','parser.py',41),
  ('parameter_list -> parameter_list COMMA parameter','parameter_list',3,'p_parameter_list','parser.py',49),
  ('parameter_list -> parameter','parameter_list',1,'p_parameter_list','parser.py',50),
  ('parameter -> INT ID','parameter',2,'p_parameter','parser.py',58),
  ('statement_list -> statement_list statement','statement_list',2,'p_stmt_list','parser.py',63),
  ('statement_list -> statement','statement_list',1,'p_stmt_list','parser.py',64),
  ('statement -> INT ID SEMICOLON','statement',3,'p_stmt_var_decl','parser.py',72),
  ('statement -> INT ID EQUALS expression SEMICOLON','statement',5,'p_stmt_var_decl','parser.py',73),
  ('statement -> ID EQUALS expression SEMICOLON','statement',4,'p_stmt_assign','parser.py',81),
  ('statement -> RETURN expression SEMICOLON','statement',3,'p_stmt_return','parser.py',86),
  ('statement -> RETURN SEMICOLON','statement',2,'p_stmt_return','parser.py',87),
  ('statement -> PRINT LPAREN expression RPAREN SEMICOLON','statement',5,'p_stmt_print','parser.py',95),
  ('expression -> term','expression',1,'p_expr_term','parser.py',100),
  ('term -> term TIMES factor','term',3,'p_term_muldiv','parser.py',105),
  ('term -> term DIVIDE factor','term',3,'p_term_muldiv','parser.py',106),
  ('term -> factor','term',1,'p_term_factor','parser.py',111),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',116),
  ('factor -> ID','factor',1,'p_factor_id','parser.py',121),
  ('factor -> ID LPAREN argument_list RPAREN','factor',4,'p_factor_call','parser.py',126),
  ('factor -> ID LPAREN RPAREN','factor',3,'p_factor_call','parser.py',127),
  ('argument_list -> argument_list COMMA expression','argument_list',3,'p_argument_list','parser.py',135),
  ('argument_list -> expression','argument_list',1,'p_argument_list','parser.py',136),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',144),
  ('expression -> expression PLUS term','expression',3,'p_expr_addsub','parser.py',149),
  ('expression -> expression MINUS term','expression',3,'p_expr_addsub','parser.py',150),
]
